import { test, expect } from '@playwright/test';

test.describe('Deep E2E: Admin Commerce Product Creation', () => {
  test('Complete Product Creation Flow', async ({ page }) => {
    // 1. Navigate to Add Product page
    await page.goto('/admin/commerce/products');
    
    // Click Add Product link
    const addProductBtn = page.getByRole('link', { name: /Add Product/i });
    if (await addProductBtn.isVisible()) {
      await addProductBtn.click();
    } else {
      await page.goto('/admin/commerce/products/new');
    }

    // 2. Fill out the Product Form
    // Wait for form to load
    await expect(page.locator('form')).toBeVisible();

    // Fill Title
    await page.getByLabel(/Title/i).fill('E2E Test eBook');

    // Fill Description
    await page.getByLabel(/Description/i).fill('This is a comprehensive test ebook generated by Playwright.');

    // Set Price
    await page.getByLabel(/Price/i).fill('499');

    // Set Type to EBOOK
    // Assuming it's a select element or a dropdown
    const typeSelect = page.getByLabel(/Product Type/i);
    if (await typeSelect.isVisible()) {
      await typeSelect.selectOption({ label: 'EBOOK' });
    }

    // 3. Submit Form
    const submitBtn = page.getByRole('button', { name: /Create Product|Save/i });
    await submitBtn.click();

    // 4. Verify Redirect & Success
    // Should go back to products list
    await expect(page).toHaveURL(/\/admin\/commerce\/products/);
    
    // Verify the new product exists in the table
    await expect(page.locator('table')).toContainText('E2E Test eBook');
  });
});
