"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowser } from "@/lib/supabase-browser";
import { Users, UserPlus, TrendingUp, Gift, Loader2 } from "lucide-react";
import { formatPrice } from "@/lib/utils";

export default function AdminDashboardOverview() {
  const [stats, setStats] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const supabase = getSupabaseBrowser();
        
        // Fetch basic counts
        const [
          { count: pendingApps },
          { count: activePartners },
          { data: partnerStats },
        ] = await Promise.all([
          supabase.from("mt_partner_applications").select("*", { count: "exact", head: true }).eq("status", "pending"),
          supabase.from("mt_partners").select("*", { count: "exact", head: true }).eq("status", "active"),
          supabase.from("mt_partners").select("total_revenue, total_commission")
        ]);

        const totalRevenue = partnerStats?.reduce((sum, p) => sum + Number(p.total_revenue || 0), 0) || 0;
        const totalCommission = partnerStats?.reduce((sum, p) => sum + Number(p.total_commission || 0), 0) || 0;

        setStats({
          pendingApps: pendingApps || 0,
          activePartners: activePartners || 0,
          totalRevenue,
          totalCommission
        });
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchStats();
  }, []);

  if (loading) {
    return <div className="flex items-center justify-center h-64"><Loader2 className="w-8 h-8 animate-spin text-emerald-600" /></div>;
  }

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Pending Apps</h3>
            <div className="w-10 h-10 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center">
              <UserPlus className="w-5 h-5" />
            </div>
          </div>
          <div className="text-3xl font-bold text-slate-900">{stats?.pendingApps}</div>
          <p className="text-sm text-slate-500 mt-2">Awaiting review</p>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Active Partners</h3>
            <div className="w-10 h-10 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center">
              <Users className="w-5 h-5" />
            </div>
          </div>
          <div className="text-3xl font-bold text-slate-900">{stats?.activePartners}</div>
          <p className="text-sm text-slate-500 mt-2">Approved marketers</p>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Total Revenue</h3>
            <div className="w-10 h-10 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center">
              <TrendingUp className="w-5 h-5" />
            </div>
          </div>
          <div className="text-3xl font-bold text-slate-900">{formatPrice(stats?.totalRevenue)}</div>
          <p className="text-sm text-slate-500 mt-2">Generated by partners</p>
        </div>

        <div className="bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">Total Commissions</h3>
            <div className="w-10 h-10 rounded-full bg-amber-50 text-amber-600 flex items-center justify-center">
              <Gift className="w-5 h-5" />
            </div>
          </div>
          <div className="text-3xl font-bold text-slate-900">{formatPrice(stats?.totalCommission)}</div>
          <p className="text-sm text-slate-500 mt-2">Lifetime partner earnings</p>
        </div>

      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 text-center mt-10">
        <div className="w-16 h-16 bg-slate-100 text-slate-400 rounded-full flex items-center justify-center mx-auto mb-4">
          <TrendingUp className="w-8 h-8" />
        </div>
        <h2 className="text-xl font-semibold text-slate-800 mb-2">Welcome to MediTonic Admin</h2>
        <p className="text-slate-500 max-w-md mx-auto">
          Use the sidebar to manage partner applications, assign referral codes, and process commission payouts.
        </p>
      </div>
    </div>
  );
}
