/** Common homeopathic remedy names for autocomplete (Latin / standard spelling). */
export const REMEDY_NAMES: readonly string[] = [
  "Aconitum napellus",
  "Aesculus hippocastanum",
  "Agaricus muscarius",
  "Allium cepa",
  "Aloe socotrina",
  "Alumina",
  "Ambra grisea",
  "Ammonium carbonicum",
  "Ammonium muriaticum",
  "Anacardium orientale",
  "Antimonium crudum",
  "Antimonium tartaricum",
  "Apis mellifica",
  "Argentum nitricum",
  "Arnica montana",
  "Arsenicum album",
  "Arsenicum iodatum",
  "Aurum metallicum",
  "Baptisia tinctoria",
  "Baryta carbonica",
  "Belladonna",
  "Berberis vulgaris",
  "Borax",
  "Bryonia alba",
  "Calcarea carbonica",
  "Calcarea phosphorica",
  "Calcarea sulphurica",
  "Calendula officinalis",
  "Camphora",
  "Cannabis indica",
  "Cantharis",
  "Carbo animalis",
  "Carbo vegetabilis",
  "Causticum",
  "Chamomilla",
  "Chelidonium majus",
  "China officinalis",
  "Cimicifuga racemosa",
  "Cina",
  "Cocculus indicus",
  "Coffea cruda",
  "Colchicum autumnale",
  "Colocynthis",
  "Conium maculatum",
  "Crataegus oxyacantha",
  "Crocus sativus",
  "Crotalus horridus",
  "Croton tiglium",
  "Cuprum metallicum",
  "Digitalis purpurea",
  "Drosera rotundifolia",
  "Dulcamara",
  "Eupatorium perfoliatum",
  "Ferrum metallicum",
  "Ferrum phosphoricum",
  "Gelsemium sempervirens",
  "Graphites",
  "Hamamelis virginiana",
  "Hepar sulphuris calcareum",
  "Hyoscyamus niger",
  "Hypericum perforatum",
  "Ignatia amara",
  "Iodium",
  "Ipecacuanha",
  "Kali bichromicum",
  "Kali carbonicum",
  "Kali iodatum",
  "Kali muriaticum",
  "Kali phosphoricum",
  "Kali sulphuricum",
  "Kreosotum",
  "Lachesis mutus",
  "Lac caninum",
  "Lac defloratum",
  "Ledum palustre",
  "Lilium tigrinum",
  "Lycopodium clavatum",
  "Lyssinum",
  "Magnesia carbonica",
  "Magnesia muriatica",
  "Magnesia phosphorica",
  "Medorrhinum",
  "Mercurius solubilis",
  "Mercurius vivus",
  "Mezereum",
  "Millefolium",
  "Moschus",
  "Muriaticum acidum",
  "Natrum carbonicum",
  "Natrum muriaticum",
  "Natrum phosphoricum",
  "Natrum sulphuricum",
  "Nitricum acidum",
  "Nux moschata",
  "Nux vomica",
  "Opium",
  "Phosphoricum acidum",
  "Phosphorus",
  "Phytolacca decandra",
  "Platina",
  "Plumbum metallicum",
  "Podophyllum peltatum",
  "Psorinum",
  "Pulsatilla nigricans",
  "Pyrogenium",
  "Rhus toxicodendron",
  "Rhus venenata",
  "Rumex crispus",
  "Ruta graveolens",
  "Sabina",
  "Sarsaparilla",
  "Secale cornutum",
  "Sepia officinalis",
  "Silicea terra",
  "Spigelia anthelmia",
  "Spongia tosta",
  "Stannum metallicum",
  "Staphysagria",
  "Stramonium",
  "Sulphur",
  "Sulphuricum acidum",
  "Symphytum officinale",
  "Syphilinum",
  "Tabacum",
  "Taraxacum officinale",
  "Tellurium",
  "Teucrium marum verum",
  "Theridion",
  "Thuja occidentalis",
  "Tuberculinum bovinum",
  "Veratrum album",
  "Viola odorata",
  "Zincum metallicum"
] as const;
